<a href="https://colab.research.google.com/github/NITIKA12K/NUMPY-PRACTICE/blob/main/Copy_of_MY_PANDAS_SERIES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IMPORTING PANDAS**

In [ ]:
import numpy as np
import pandas as pd

# **Series from lists**

In [ ]:
#string
country=["india",'pakistan','newyork','malaysia']
pd.Series(country)           # CAPITAL S

0       india
1    pakistan
2     newyork
3    malaysia
dtype: object

In [ ]:
#integers
runs=[87,88,00,22,22]
runs_ser=pd.Series(runs)

In [ ]:
#custom index + #Setting a name
marks=[89,67,45,78,98]
subjects=['maths','hindi','english','DBMS','GMGJ']
marks=pd.Series(marks,index=subjects,name='nitika ke marks')
marks

maths      89
hindi      67
english    45
DBMS       78
GMGJ       98
Name: nitika ke marks, dtype: int64

# **Series from dict**

In [ ]:
marks={                               #in dictonary you don't have to mention that this is  your index
    'english':56,
    'maths' :88,
    'hghjgj' :77,
    'oopws':88
}
marks_series=pd.Series(marks,name='nitika ke marks')
marks_series

english    56
maths      88
hghjgj     77
oopws      88
Name: nitika ke marks, dtype: int64

# **Series Attributes**

In [ ]:
#size
marks_series.size

4

In [ ]:
#dtype
marks_series.dtype

dtype('int64')

In [ ]:
#name
marks_series.name

'nitika ke marks'

In [ ]:
#is_unique
marks_series.is_unique

False

In [ ]:
pd.Series([1,11,2,1,1]).is_unique

False

In [ ]:
#index
marks_series.index

Index(['english', 'maths', 'hghjgj', 'oopws'], dtype='object')

In [ ]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#values
marks_series.values         #it means it give array numpy array

array([56, 88, 77, 88])

In [ ]:
type(marks_series.values)

numpy.ndarray

In [ ]:
from google.colab import drive
drive.mount('/content/drive')